export const modelConfig = {
  xs: {
    reinald: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      scaleX: 2,
      scaleY: 2,
      scaleZ: 2,
    },
    coding: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 6,
      scaleY: 6,
      scaleZ: 6,
    },
    waveform: {
      x: 2,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
  sm: {
    reinald: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      scaleX: 2,
      scaleY: 2,
      scaleZ: 2,
    },
    coding: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 6,
      scaleY: 6,
      scaleZ: 6,
    },
    waveform: {
      x: 2,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
  md: {
    reinald: {
      x: -3,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 1.45,
      scaleY: 1.45,
      scaleZ: 1.45,
    },
    coding: {
      x: 2,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 7.5,
      scaleY: 7.5,
      scaleZ: 7.5,
    },
    waveform: {
      x: -2,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
  lg: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 3.5,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
    waveform: {
      x: -3,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
  xl: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
    waveform: {
      x: -4,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
  xxl: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
    waveform: {
      x: -4,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
  xxxl: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
    waveform: {
      x: -4,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
    },
  },
}

export const textModelConfig = {
  xs: [
    ["HI\nI'M REINALD", { size: 0.45, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.48, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.55, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ["LET'S\nCONNECT", { size: 0.5, offsets: { x: 0, y: 1, z: 0 } }],
  ],
  sm: [
    ["HI\nI'M REINALD", { size: 0.4, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ["LET'S\nCONNECT", { size: 0.5, offsets: { x: 0, y: 1, z: 0 } }],
  ],
  md: [
    ["HI\nI'M REINALD", { size: 0.55, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.65, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.65, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  lg: [
    ["HI\nI'M REINALD", { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 2.5, offsets: { x: -4.5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0.5, z: 0 } }],
  ],
  xl: [
    ["HI\nI'M REINALD", { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 3.5, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 0.9, offsets: { x: 0, y: 0.5, z: 0 } }],
  ],
  xxl: [
    ["HI\nI'M REINALD", { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.91, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 1.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 4, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0.5, z: 0 } }],
  ],
  xxxl: [
    ["HI\nI'M REINALD", { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE\nDEVELOPER', { size: 0.91, offsets: { x: 0, y: 0, z: 0 } }],
    ['SOUND\nDESIGNER', { size: 0.9, offsets: { x: 0, y: 0, z: 0 } }],
    ['PROJECTS', { size: 1.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 4, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0.5, z: 0 } }],
  ],
}

// export const codingText = `function make() {\n<tab>inNeedOfHelp = true\nisReinaldAvailable = true\nisCoffeeReady = true\n\nif (inNeedOfHelp && isReinaldAvailable && isCoffeeReady) {\n<tab>return "Reinald is here to help!"\n<-tab>}\n<-tab>}`
export const textCoding = `function make() {\n<tab>inNeedOfHelp = true\nisReinaldAvailable = true\nisCoffeeReady = true\n\nif (\n<tab>inNeedOfHelp &&\nisReinaldAvailable &&\nisCoffeeReady\n<-tab>) {\n<tab>return "Reinald is here to help!"\n<-tab>}\n<-tab>}`

export const textCodingConfig = {
  xs: {
    size: 0.1,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 0.25,
  },
  sm: {
    size: 0.15,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 0.3,
  },
  md: {
    size: 0.15,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 0.35,
  },
  lg: {
    size: 0.2,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 0.4,
  },
  xl: {
    size: 0.225,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 0.75,
  },
  xxl: {
    size: 0.3,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 0.875,
  },
  xxxl: {
    size: 0.35,
    offsets: { x: 0, y: 0, z: 0 },
    tab: 1.0,
  },
}
