export const modelConfig = {
  xs: {
    reinald: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      scaleX: 2,
      scaleY: 2,
      scaleZ: 2,
    },
    coding: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 6,
      scaleY: 6,
      scaleZ: 6,
    },
  },
  sm: {
    reinald: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      scaleX: 2,
      scaleY: 2,
      scaleZ: 2,
    },
    coding: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 6,
      scaleY: 6,
      scaleZ: 6,
    },
  },
  md: {
    reinald: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      scaleX: 2,
      scaleY: 2,
      scaleZ: 2,
    },
    coding: {
      x: 0,
      y: 0,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 6,
      scaleY: 6,
      scaleZ: 6,
    },
  },
  lg: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
  },
  xl: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
  },
  xxl: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
  },
  xxxl: {
    reinald: {
      x: -4,
      y: -1.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * 0.25,
      rotateZ: 0,
      scaleX: 2.5,
      scaleY: 2.5,
      scaleZ: 2.5,
    },
    coding: {
      x: 4,
      y: -0.5,
      z: 0,
      rotateX: 0,
      rotateY: Math.PI * -0.25,
      rotateZ: 0,
      scaleX: 10,
      scaleY: 10,
      scaleZ: 10,
    },
  },
}

export const textModelConfig = {
  xs: [
    ["HI, I'M REINALD", { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  sm: [
    ["HI, I'M REINALD", { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  md: [
    ["HI, I'M REINALD", { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 0.5, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  lg: [
    ["HI, I'M REINALD", { size: 1.2, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1.5, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  xl: [
    ["HI, I'M REINALD", { size: 1.2, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1.8, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  xxl: [
    ["HI, I'M REINALD", { size: 1.2, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1.8, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
  xxxl: [
    ["HI, I'M REINALD", { size: 1.2, offsets: { x: 0, y: 0, z: 0 } }],
    ['CREATIVE', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['DEVELOPER', { size: 1.3, offsets: { x: 0, y: 0, z: 0 } }],
    ['XP', { size: 1.8, offsets: { x: -5, y: 0, z: 0 } }],
    ["LET'S CONNECT", { size: 1, offsets: { x: 0, y: 0, z: 0 } }],
  ],
}
